### PR TITLE
Distinct Strimzi Logo for Light and Dark Modes

### LINKED ISSUE #6: The logo on the Strimzi profile page does not align with the screen mode, whether it's in Light or Dark mode
Before 
1.

image

[Link](https://github.com/strimzi)

2.
image

[Link](https://github.com/strimzi/.github)

After

Ideally, the logo should appear white in Dark mode and retain its normal appearance in Light mode.

image

image

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Fixes: #6

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
@scholzj Please take a look at it.

**Review by scholzj — APPROVED** [review]
The HTML is not nice, but not sure there is better way to do it. LGTM assuming it works.

**Comment by ppatierno** [comment]
@UtkarshMishra12 did you try on different browsers (Chrome, Firefox and Edge at least) and on mobile?

**Comment by UtkarshMishra12** [comment]
@ppatierno Yes, it's working perfectly on all browsers and mobile devices.

**Comment by ppatierno** [comment]
Perfect thanks!

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
